# Modified by sentei (see PATCHES.md); original: Workiva/scip-dart 1.7.0, Apache-2.0.
name: scip_dart
version: 1.7.0
description: generates scip bindings for dart files
repository: https://github.com/Workiva/scip-dart

environment:
  sdk: ">=3.11.0 <4.0.0"

executables:
  scip_dart:

dependencies:
  analyzer: ^14.0.0
  args: ^2.4.0
  package_config: ^3.0.0
  path: ^1.8.3
  protobuf: ^3.1.0
  pubspec_parse: ^1.2.1
  pubspec_lock_parse: ^2.2.0
  collection: ^1.18.0
